/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package overcooked.fide;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Josuu
 */
public class PantallaInicio extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio
     */
    
    // Hacemos get de la instancia del Jugador
    // Se cambió por el get porque el new lo que hacía era crear un objeto nuevo cada vez que se devolvía al menú
    // por eso se borraban los datos del jugador ggwp
    
    Jugador jugador = Jugador.getInstance();

    public PantallaInicio() 
    {
        initComponents();
        activarCancionInicio();
        activarImagenes();
        
        // Setear posición a la pantalla
        setLocationRelativeTo(null);
        setResizable(false);   
        
        grupoGenero.add(f);
        grupoGenero.add(m);

        // Mostrar los datos del jugador en los campos correspondientes cada vez que se devuelva al menú
        txtNombre.setText(jugador.getNombre());
        if (jugador.getGenero() != null) {
            if (jugador.getGenero().equalsIgnoreCase("M")) 
            {
                m.setSelected(true);
            } 
            else if (jugador.getGenero().equalsIgnoreCase("F")) 
            {
                f.setSelected(true);
            }
        }
    
    }

    public final void activarCancionInicio() 
    {
        Reproductor_Musica reproductor = Reproductor_Musica.getInstance();
        if (!reproductor.reproduciendo) 
        {
            Thread hiloMusica = new Thread(reproductor);
            hiloMusica.start();
        }
    }
    
    public final void activarImagenes(){

        //Se crea un objeto Icon con la libreria Icon, se le pasa la posición 
        //del label 
        Icon header = new ImageIcon(new ImageIcon
        (getClass().getResource("overcookedheader.png")).getImage().getScaledInstance
        (lblImageHeader.getWidth(), lblImageHeader.getHeight(), 
        0));
       
        // Se le setea el Icon a el label
        lblImageHeader.setIcon(header);
        
        if(jugador.getIdentificado() == null){
            
            Icon user = new ImageIcon(new ImageIcon
            (getClass().getResource("user.png")).getImage().getScaledInstance
            (lblImageUser.getWidth(), lblImageUser.getHeight(), 
            0));
            
            lblImageUser.setIcon(user); 
   
        }else{
            
            actualizarImagenes();
        
        } 
    }
    
    public void actualizarImagenes(){
        
        String genero = jugador.getGenero();

        if(genero != null && genero.equalsIgnoreCase("M")){
            
           Icon manPlayer = new ImageIcon(new ImageIcon
            (getClass().getResource("manPlayer.png")).getImage().getScaledInstance
            (lblImageUser.getWidth(), lblImageUser.getHeight(), 
            0)); 
           
           lblImageUser.setIcon(manPlayer);  
           
        }else if(genero != null && genero.equalsIgnoreCase("F")){
            
            Icon womanPlayer = new ImageIcon(new ImageIcon
            (getClass().getResource("womanPlayer.png")).getImage().getScaledInstance
            (lblImageUser.getWidth(), lblImageUser.getHeight(), 
            0));
            
            lblImageUser.setIcon(womanPlayer);  
            
        }  
    }
    
    public void iniciarSesion(){

        if(!txtNombre.getText().isEmpty()){
            
            if(m.isSelected() || f.isSelected()){
                
                jugador.setNombre(txtNombre.getText());
                jugador.setIdentificado(true);
                
                if(m.isSelected()){
                    
                    jugador.setGenero("M"); 
                }else{
                    
                    jugador.setGenero("F"); 
                }
                JOptionPane.showMessageDialog
                (null,"Guardado Correctamente");
                
                actualizarImagenes();
                
            }else{
                
                JOptionPane.showMessageDialog
            (null,"Debe llenar el campo de "
                            + "genero para continuar");
                
            }
        }else{
            
            JOptionPane.showMessageDialog
            (null,"Debe llenar el campo de nombre "
                            + " para continuar");
        
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoGenero = new javax.swing.ButtonGroup();
        lblImageHeader = new javax.swing.JLabel();
        btnPuntuaciones = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblImageUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPuntuaciones.setBackground(new java.awt.Color(0, 153, 153));
        btnPuntuaciones.setText("Puntuaciones");
        btnPuntuaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntuacionesActionPerformed(evt);
            }
        });

        btnJugar.setBackground(new java.awt.Color(0, 153, 153));
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblImageUser.setBackground(new java.awt.Color(255, 153, 153));
        lblImageUser.setForeground(new java.awt.Color(255, 153, 153));

        jLabel1.setText("Nombre:");

        m.setText("M");

        f.setText("F");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPuntuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardar)
                                    .addComponent(f))))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPuntuaciones)
                            .addComponent(btnJugar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m)
                            .addComponent(f))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        JOptionPane.showMessageDialog(null,"Muchas gracias por jugar!","Saliendo....",JOptionPane.INFORMATION_MESSAGE);
        
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPuntuacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntuacionesActionPerformed
        Puntuaciones mostrar_puntuaciones = new Puntuaciones(); 
        mostrar_puntuaciones.setVisible(true); 
        mostrar_puntuaciones.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPuntuacionesActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        
        if(jugador.getIdentificado() == null){
            
            JOptionPane.showMessageDialog
            (null,"Debe Identificarse antes de jugar");
        
        }else{
            
            Juego mostrar_juego = new Juego(); 
            mostrar_juego.setVisible(true); 
            mostrar_juego.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btnJugarActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        iniciarSesion();        
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPuntuaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JRadioButton f;
    private javax.swing.ButtonGroup grupoGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImageHeader;
    private javax.swing.JLabel lblImageUser;
    private javax.swing.JRadioButton m;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
